# Generated by Django 5.1 on 2024-12-19 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('media', models.FileField(upload_to='posts/')),
                ('dateCreation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-dateCreation'],
            },
        ),
    ]
