services:
  - type: web
    name: tiktak
    env: python
    buildCommand: |
      # Assurez-vous que les dépendances sont installées correctement
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py makemigrations
      python manage.py migrate
      python manage.py runserver
    startCommand: gunicorn TikTak.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tiktak_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,3.75.158.163,3.125.183.140,35.157.117.28,127.0.0.1"
      - key: HOST_NAME
        value: "dpg-cthf8c1u0jms7384buog-a"

      - key: PASSWORD
        value: "z24poCVNtBpSzZxvuLfDfcOZrxHcttGZ"
      - key: USERNAME
        value: "demo"
      - key: DATABASE
        value: "tiktak_fkgz"

databases:
  - name: tiktak_db
    databaseName: tiktak
    user: demo
    starterPlan: true # Utilise un plan gratuit pour commencer